### ISSUE TITLE
Medbay maintenance access open to all

### ISSUE THREAD

**Issue by TatsumakiMagi** [FTL13/FTL13#74]
**Problem Description**:
Anyone with maintenance access can pass into medbay via their maintenance door.

**What did you expect to happen**: 
Medbay maintenance door should not have opened to me because I was part of the cargo department

**What happened instead**:
The maintenance door to medbay opened and allowed me to pass through.

**Why is this bad/What are the consequences:**
Anyone with antag objectives would be able to pass into medbay and cause problems. 

**Steps to reproduce the problem**:
I Joined the game as a cargo technician, passed into the maintenance area and passed into medbay using the maintenance door.

**Comment by TatsumakiMagi** [comment]
This problem still happened on the test server, I was a miner if that makes any difference.

**Comment by CrAzYPiLoT-SS13** [comment]
Did you update from the repo after I pushed this?

**Comment by ProcessedSpecimen** [comment]
Just checked the access after playing a game and yes, the problem is still happening.

This time I was a station engineer, I could walk through the maintenance door to the right of medbay and then go through the door that opens up nearby the cryotube and access medbay that way.
